=== yaxis1/datapipelines/advisor/advisors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
    <xs:element name = "advisorinfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "firstname">
                    <xs:simpleType>
                        <xs:restriction base = "xs:string" >
                            <xs:pattern value="([A-Z])+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name = "lastname" type = "xs:string"/>
                <xs:element name = "employeeid" type= "xs:integer"/>
                <xs:element name = 'clients_managing'>
                    <xs:complexType>
                        
                        <xs:sequence>
                            <xs:element name = 'client_info' type = 'client_information'
                                minOccurs='1' maxOccurs="unbounded"/>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name ="client_information">
        <xs:sequence>
            <xs:element name = 'clientid' >
                <xs:simpleType>
                    <xs:restriction base = "xs:integer" >
                        <xs:minInclusive value="100"/>
                        <xs:maxInclusive value="9999"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name = "insurance_granted" type="xs:boolean" minOccurs="1"/>
            <xs:element name = "insurance_type">
                <xs:simpleType>
                    <xs:restriction base = "xs:string">
                        <xs:enumeration value="Health insurance"/>
                        <xs:enumeration value="Car insurance"/>
                        <xs:enumeration value="Life insurance"/>
                        <xs:enumeration value="Travel insurance"/>
                        <xs:enumeration value="Home insurance"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
        </xs:sequence>
    </xs:complexType>
    
    
    
    
    
    
</xs:schema>

=== yaxis1/datapipelines/advisor/advisor.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href='advisors.xsl'?>

<advisorinfo xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "advisors.xsd">
    <firstname>BALA</firstname>
    <lastname>Veerabatti</lastname>
    <employeeid>6</employeeid>
    <clients_managing>
        <client_info>
            <clientid>101</clientid>
            <insurance_granted>true</insurance_granted>
            <insurance_type>Health insurance</insurance_type>
        </client_info>
        
        <client_info>
            <clientid>101</clientid>
            <insurance_granted>false</insurance_granted>
            <insurance_type>Car insurance</insurance_type>
        </client_info>
        
        <client_info>
            <clientid>102</clientid>
            <insurance_granted>false</insurance_granted>
            <insurance_type>Car insurance</insurance_type>
        </client_info>
        
        <client_info>
            <clientid>103</clientid>
            <insurance_granted>false</insurance_granted>
            <insurance_type>Life insurance</insurance_type>
        </client_info>
       
    </clients_managing>
</advisorinfo>
