=== yaxis1/datapipelines/insurance/insurance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
 <xs:element name="insurances">
     <xs:complexType>
         <xs:sequence>
    
    <xs:element name = "insurance" maxOccurs="unbounded">
        <xs:complexType > 
            <xs:sequence >
                <xs:element name = "contract_id" type = 'xs:integer'/>
                <xs:element name = 'clientid'>
                    <xs:simpleType>
                        <xs:restriction base = "xs:integer" >
                            <xs:minInclusive value="100"/>
                            <xs:maxInclusive value="9999"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name = "employeeid" type = 'xs:integer'/>
                <xs:element name = "begin_contract_date" type = "xs:date"/>
                <xs:element name = "end_contract_date" type = "xs:date"/>
                <xs:element name = "insurance_type">
                    <xs:simpleType >
                        <xs:restriction base = "xs:string">
                            <xs:enumeration value="Health insurance"/>
                            <xs:enumeration value="Car insurance"/>
                            <xs:enumeration value="Life insurance"/>
                            <xs:enumeration value="Travel insurance"/>
                            <xs:enumeration value="Home insurance"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
         </xs:sequence>
     </xs:complexType>
 </xs:element>

    
    
</xs:schema>

=== yaxis1/datapipelines/insurance/insurance.xml
<?xml version="1.0" encoding="UTF-8"?>


<?xml-stylesheet type="text/xsl" href='insurance.xsl'?>


<?xmlns xs="http://www.w3.org/2001/XMLSchema"?>
<insurances xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "insurance.xsd">
    <insurance>
        <contract_id>007</contract_id>
        <clientid>101</clientid>
        <employeeid>6</employeeid>
        <begin_contract_date>2012-08-12</begin_contract_date>
        <end_contract_date>2020-10-18</end_contract_date>
        <insurance_type>Car insurance</insurance_type>
    </insurance>
    
    <insurance>
        <contract_id>008</contract_id>
        <clientid>102</clientid>
        <employeeid>7</employeeid>
        <begin_contract_date>2010-11-13</begin_contract_date>
        <end_contract_date>2020-10-18</end_contract_date>
        <insurance_type>Travel insurance</insurance_type>
    </insurance>
    
    
    <insurance>
        
        <contract_id>009</contract_id>
        <clientid>101</clientid>
        <employeeid>8</employeeid>
        <begin_contract_date>2012-12-13</begin_contract_date>
        <end_contract_date>2004-11-15</end_contract_date>
        <insurance_type>Health insurance</insurance_type>
        
    </insurance>
    
    <insurance>
        
        <contract_id>012</contract_id>
        <clientid>102</clientid>
        <employeeid>10</employeeid>
        <begin_contract_date>1995-05-10</begin_contract_date>
        <end_contract_date>2020-12-13</end_contract_date>
        <insurance_type>Life insurance</insurance_type>
        
    </insurance>
    
    <insurance>
        
        <contract_id>012</contract_id>
        <clientid>102</clientid>
        <employeeid>10</employeeid>
        <begin_contract_date>1995-04-10</begin_contract_date>
        <end_contract_date>2020-12-18</end_contract_date>
        <insurance_type>Home insurance</insurance_type>
        
    </insurance>
    
    
</insurances>
